### ISSUE TITLE
Great Project.. how to get involved?

### ISSUE THREAD

**Issue by digitaledge** [OpherV/Incheon#13]
Hello, 
could i participate in development?  I run a modified version of your code here with BabylonJS Renderer and Cannon Physics on server side. Maybe we could share skype contacts?  

Regards
Stefan

**Comment by OpherV** [comment]
Hi @digitaledge !
I'm super curious - how did you hear about this project? And how did you get it to work? It's not even stable enough for our use :)

In any case things are very shifty as me and @namel are working hard on the alpha release. Once that's out with some documentation in the near future we will gladly accept assistance from the open source/gamedev community.

If you want to take on topic that's on our todo list, you can research whether it's possible to use UDP with WebRTC data instead of TCP and Socket.IO. Having that option will increase performance significantly.

For further questions please contact me at opherv@gmail.com
