### ISSUE TITLE
Elements do not appear to move/ client does not run

### ISSUE THREAD

**Issue by MurkyA** [OpherV/Incheon#14]
When I run netpong, the server seems to be operating, but when I connect in my browser I only see the two paddles stuck at the top of the screen at their respective locations and the ball stuck at the top left. The server still reports new connections and disconnections and announces that players are scoring. The method that responds to user input does not appear to execute on the server when I press keys in the browser. 

When I connect to spaaace, I only see a white screen. 

I'm using windows 10. This happens with both chrome and firefox.

**Comment by OpherV** [comment]
Glad to have you here @MurkyA! :) 
Incheon hasn't been "officially" released yet.  We're gearing up towards the 1.0 release hopefully in the next couple of weeks. 

This means netpong is a bit broken due to last minute api change,  but you can test spaaace against the develop branch of Incheon and it should work fine (though not completely finished)

**Comment by OpherV** [comment]
@MurkyA Incheon is officially released!
