### ISSUE TITLE
[Question] Would this be a good candidate for an RTS game? EOM

### ISSUE THREAD

**Issue by QuantumInformation** [OpherV/Incheon#23]
I am making a game called density wars: https://www.youtube.com/watch?v=i7tdJpf6Pnc
using babylonjs.

I've been delaying for a while and want to get the game up and running.

https://github.com/QuantumInformation/Density-Wars

**Comment by OpherV** [comment]
Yes! You might want to go with interpolation sync method rather than extrapolation in this use case.  Also,  I saw that you're using Babylon js. We have experience working with  three js,  but as Incheon is game and renderer agnostic,  this means you can hook into your own Babylon  renderer. It's a bit more work but doable. 

You're welcome join us on slack to discuss this 
http://slack.incheon.gg/
